title: Weilin Ruan (阮炜霖)
subtitle: Academic Style Personal Page
description: All things come to those who wait.
url: https://rwlinno.github.io
baseurl: ""
author : RWLinno
language : 
timezone: China/Beijing
permalink:   /:categories/:title

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:path/

# Owner/author information
owner:
  name: Weilin Ruan (阮炜霖)
  avatar: images/4000x4000ce.jpg
#  bio:
  email: rwlinno@gmail.com
  # Social networking links are used in author-bio sidebar
  github: rwlinno
  scholar: https://scholar.google.com/citations?user=9uk1jJoAAAAJ
  openreview: https://openreview.net/profile?id=~Weilin_Ruan2
  twitter: rwlinno
  CSDN: SC_Linno
  bilibili: 6954236

# Site navigation is handled by _data/navigation.yml

# Jekyll settings
future: true
highlighter: rouge
markdown: kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

# Build settings
include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", ".DS_Store", "node_modules", "vendor"]

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag